
spool C:\Users\melis\OneDrive\Escritorio\Vuelos.txt

set linesize 300
set pagesize 90
set feddback on
set colsep ' ||' 
clear screen 


--Cambiar idioma 
ALTER SESSION SET NLS_DATE_LANGUAGE  = 'ENGLISH';

--Borrar tablas
DROP TABLE VUELOS;

--Crear tabla

CREATE TABLE VUELOS (
    PILOT VARCHAR2(15),
    FLIGHT NUMBER(3),
    FECHA TIMESTAMP
);

--Insertar datos

INSERT INTO VUELOS VALUES ('ALEXANDRA', 231, '05/12/2018');
INSERT INTO VUELOS VALUES ('MELISSA', 132, '01/01/2020');
INSERT INTO VUELOS VALUES ('ANGELICA', 245, '02/01/2020');
INSERT INTO VUELOS VALUES ('YAEL', 211, '03/03/2020');
INSERT INTO VUELOS VALUES ('JHONY', 127, '06/04/2020');
INSERT INTO VUELOS VALUES ('JUAN', 133, '01/01/2020');
INSERT INTO VUELOS VALUES ('ALEX', 232, '01/09/2021');
INSERT INTO VUELOS VALUES ('SOFIA', 492, '21/01/2020');
INSERT INTO VUELOS VALUES ('MARCO', 818, '01/01/2023');
INSERT INTO VUELOS VALUES ('RUBEN', 081, '15/03/2021');
INSERT INTO VUELOS VALUES ('VALERIA', 223, '01/05/2020');

--Consultas


SELECT FLIGHT VUELO,
         PILOT PILOTO,
         TO_CHAR(FECHA, 'DD/MM/YYYY HH24:MI:SS') FECHA
FROM VUELOS;

--ORDENADOS POR VUELOS

SELECT FLIGHT VUELO,
         PILOT PILOTO,
         TO_CHAR(FECHA, 'DD/MM/YYYY HH24:MI:SS') FECHA
         FROM VUELOS
         ORDER BY 1;


--CONFIGURAR PAG Y LINEA

set colsep ' ||'
COLUMN FECHA FORMAT A27
COLUMN HORAS_MIN FORMAT A15
SELECT FLIGHT AS VUELO,
       PILOT AS PILOTO,
       TO_CHAR(FECHA, 'DD/MM/YYYY') AS FECHA,
       EXTRACT(HOUR FROM FECHA) || ':' || EXTRACT(MINUTE FROM FECHA) AS HORAS_MIN
FROM VUELOS
ORDER BY 1;

--ORDENAR POR HORAS DE SALIDA

SELECT FLIGHT AS VUELO,
       PILOT AS PILOTO,
       TO_CHAR(FECHA, 'DD/MM/YYYY') AS FECHA,
       EXTRACT(HOUR FROM FECHA) || ':' || EXTRACT(MINUTE FROM FECHA) AS HORAS_MIN
FROM VUELOS
ORDER BY HORAS_MIN;

spool off

