SPOOL C:\BD\EMPLOYEE\EMPLOYEE.txt

REM ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; 
REM CREATE USER empleado IDENTIFIED by empleado
REM DEFAULT TABLESPACE users
REM TEMPORARY TABLESPACE temp;
REM GRANT CONNECT, RESOURCE TO empleado;
REM GRANT UNLIMITED TABLESPACE TO empleado;

--Ajustes de sistema
set linesize 300
set pagesize 50
set feddback on
set colsep ' ||' 
set null s/dato
clear screen 

--Cambiar idioma 
ALTER SESSION SET NLS_DATE_LANGUAGE  = 'ENGLISH';

--Borrar tablas 
DROP TABLE EMPLOYEE    CASCADE CONSTRAINTS;
DROP TABLE SECRETARY   CASCADE CONSTRAINTS;
DROP TABLE TECHNICIAN  CASCADE CONSTRAINTS; 
DROP TABLE ENGINEER    CASCADE CONSTRAINTS;

--Crear tablas 
CREATE TABLE EMPLOYEE(
	FNAME      VARCHAR2(10) NOT NULL,
	LNAME      VARCHAR2(10) NOT NULL,
	MINIT      VARCHAR2(10),
	SSN        VARCHAR2(11)  NOT NULL,
	BIRTH_DATE DATE         NOT NULL,
	ADRESS     VARCHAR2(25) NOT NULL,
	JOB_TYPE   VARCHAR2(10) NOT NULL);

CREATE TABLE SECRETARY(
	SSN          VARCHAR2(11),
	TYPING_SPEED VARCHAR2(10) NOT NULL);

CREATE TABLE TECHNICIAN(
	SSN     VARCHAR2(11)  NOT NULL,
	T_GRADE VARCHAR2(1)   NOT NULL);

CREATE TABLE ENGINEER(
	SSN VARCHAR2(11)      NOT NULL,
	ENG_TYPE VARCHAR2(20) NOT NULL);

--Restricciones PK 
ALTER TABLE EMPLOYEE
	ADD CONSTRAINT PK_SSN_EMPLOYEE PRIMARY KEY (SSN);

ALTER TABLE SECRETARY
	ADD CONSTRAINT PK_SSN_SECRETARY PRIMARY KEY (SSN);

ALTER TABLE TECHNICIAN 
	ADD CONSTRAINT PK_SSN_TECHNICIAN PRIMARY KEY(SSN);

ALTER TABLE ENGINEER
	ADD CONSTRAINT PK_SSN_ENGINEER PRIMARY KEY (SSN);

--Restricciones FK
ALTER TABLE SECRETARY 
	ADD CONSTRAINT FK_SSN_SECRETARY FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE TECHNICIAN 
	ADD CONSTRAINT FK_SSN_TECHNICIAN FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE ENGINEER 
	ADD CONSTRAINT FK_SSN_ENGINEER FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN);

--Restricciones Check 
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT EMPLOYEE_JOB_TYPE_CK CHECK (JOB_TYPE IN ('Secretary','Technician','Engineer'));

ALTER TABLE TECHNICIAN
	ADD CONSTRAINT TECHNICIAN_T_GRADE_CK CHECK (T_GRADE IN('A','B', 'C'));


--Poblar tablas 

--EMPLOYEE
INSERT INTO EMPLOYEE (FNAME, LNAME, MINIT, SSN, BIRTH_DATE, ADRESS, JOB_TYPE)
VALUES ('John', 'Doe', 'M', '111-111-111', '31/05/2001', '123 Main St', 'Secretary');

INSERT INTO EMPLOYEE (FNAME, LNAME, MINIT, SSN, BIRTH_DATE, ADRESS, JOB_TYPE)
VALUES ('Jane', 'Smith', 'A', '222-222-222', '14/05/2004', '456 Oak St', 'Technician');

INSERT INTO EMPLOYEE (FNAME, LNAME, MINIT, SSN, BIRTH_DATE, ADRESS, JOB_TYPE)
VALUES ('Robert', 'Johnson', 'B', '333-333-333', '02/03/2001', '789 Elm St', 'Engineer');

INSERT INTO EMPLOYEE (FNAME, LNAME, MINIT, SSN, BIRTH_DATE, ADRESS, JOB_TYPE)
VALUES ('Susan', 'Williams', 'C', '444-444-444', '16/03/2005', '101 Pine Ave', 'Secretary');

INSERT INTO EMPLOYEE (FNAME, LNAME, MINIT, SSN, BIRTH_DATE, ADRESS, JOB_TYPE)
VALUES ('Michael', 'Brown', 'D', '555-555-555', '03/04/2004', '202 Cedar Dr', 'Technician');


--SECRETARY
INSERT INTO SECRETARY (SSN, TYPING_SPEED)
VALUES ('111-111-111', 'Fast');

INSERT INTO SECRETARY (SSN, TYPING_SPEED)
VALUES ('222-222-222', 'Very Fast');

INSERT INTO SECRETARY (SSN, TYPING_SPEED)
VALUES ('333-333-333', 'Super Fast');

INSERT INTO SECRETARY (SSN, TYPING_SPEED)
VALUES ('444-444-444', 'Medium');

INSERT INTO SECRETARY (SSN, TYPING_SPEED)
VALUES ('555-555-555', 'Slow');


--TECHNICIAN
INSERT INTO TECHNICIAN (SSN, T_GRADE)
VALUES ('111-111-111', 'A');

INSERT INTO TECHNICIAN (SSN, T_GRADE)
VALUES ('222-222-222', 'B');

INSERT INTO TECHNICIAN (SSN, T_GRADE)
VALUES ('333-333-333', 'C');

INSERT INTO TECHNICIAN (SSN, T_GRADE)
VALUES ('444-444-444', 'B');

INSERT INTO TECHNICIAN (SSN, T_GRADE)
VALUES ('555-555-555', 'A');


--ENGINEER
INSERT INTO ENGINEER (SSN, ENG_TYPE)
VALUES ('111-111-111', 'Mechanical Engineer');

INSERT INTO ENGINEER (SSN, ENG_TYPE)
VALUES ('222-222-222', 'Civil Engineer');

INSERT INTO ENGINEER (SSN, ENG_TYPE)
VALUES ('333-333-333', 'Electrical Engineer');

INSERT INTO ENGINEER (SSN, ENG_TYPE)
VALUES ('444-444-444', 'Software Engineer');

INSERT INTO ENGINEER (SSN, ENG_TYPE)
VALUES ('555-555-555', 'Chemical Engineer');


--Consultas 
--Obtener empleados y tipo de trabajo 
SELECT FNAME, LNAME, JOB_TYPE
FROM EMPLOYEE;

--Encontrar nombres y su tipo de trabajo de ingenieros 
SELECT FNAME, LNAME, JOB_TYPE
FROM EMPLOYEE
WHERE JOB_TYPE = 'Engineer';

--Encontrar técnicos con grado A 
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE SSN IN (SELECT SSN FROM TECHNICIAN WHERE T_GRADE = 'A');

--Encontrar ingenieros que no son de software engineer 
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE SSN IN (SELECT SSN FROM ENGINEER WHERE ENG_TYPE <> 'Software Engineer');

--Obtener empleados que tienen una dirección con "St":
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE INSTR(ADRESS, 'St') > 0;

--Encontrar los nombres y tipos de trabajo de los empleados que no sean ingenieros
SELECT FNAME, LNAME, JOB_TYPE
FROM EMPLOYEE
WHERE JOB_TYPE <> 'Engineer';


--Columnas de usuario
COL TABLE_NAME FORMAT A15
COL DATA_TYPE  FORMAT A15
COL DATA_SCALE FORMAT 999.99
COL NULLABLE   FORMAT A2
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH,
	DATA_PRECISION,DATA_SCALE,NULLABLE
	FROM USER_TAB_COLUMNS 
	WHERE TABLE_NAME IN ( 'EMPLOYEE','SECRETARY','TECHNICIAN','ENGINEER')
	ORDER BY 1,2;

--Mostrar Restricciones
prompt USER CONSTRAINTS
COLUMN CONSTRAINT_NAME FORMAT A27
column table_name format a12
column owner format a9
select owner,table_name,constraint_name,constraint_type,
	deferrable,deferred
	from user_constraints
	where table_name IN ('EMPLOYEE','SECRETARY','TECHNICIAN','ENGINEER')
	ORDER BY 4;

--Mostrar objetos del usuario
COL OBJECT_NAME FORMAT A25
COL OBJECT__TYPE FORMAT A12
COL OBJECT_ID   FORMAT 99,999	
SELECT OBJECT_NAME, OBJECT_TYPE, OBJECT_ID
	FROM USER_OBJECTS
	WHERE OBJECT_TYPE IN ('TABLE','INDEX', 'VIEW')
	ORDER BY 2,1;

--Mostrar índices
COL INDEX_NAME FORMAT A20
COL TABLE_NAME FORMAT A30
COL COLUMN_NAME FORMAT A15
COL COLUMN_POSITION FORMAT 999
COL COLUMN_LENGTH   FORMAT 999
select index_name, table_name,column_name, column_position, column_length
	char_length
	from user_ind_columns
	where table_name in ('EMPLOYEE','SECRETARY','TECHNICIAN','ENGINEER');

SPOOL OFF 


